# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "geerlingguy/ubuntu1604"

  # config.vm.box_check_update = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.101"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.name = "pglogical-replica"
  end

  # provisioning
  config.vm.provision "shell", inline: <<-SHELL
    sudo echo "deb [arch=amd64] http://packages.2ndquadrant.com/pglogical/apt/ xenial-2ndquadrant main" > /etc/apt/sources.list.d/2ndquadrant.list
    wget --quiet -O - http://packages.2ndquadrant.com/pglogical/apt/AA7A6805.asc | sudo apt-key add -
    sudo apt-get update
    sudo apt-get dist-upgrade -y
    sudo apt-get install postgresql -y
    sudo apt-get install postgresql-9.5-pglogical -y
    sudo sed -i "59 i listen_addresses = '*'" /etc/postgresql/9.5/main/postgresql.conf
    sudo sed -i "149 i shared_preload_libraries = 'pglogical'" /etc/postgresql/9.5/main/postgresql.conf
    sudo sed -i "177 i wal_level = 'logical'" /etc/postgresql/9.5/main/postgresql.conf
    sudo sed -i "229 i max_wal_senders = 10" /etc/postgresql/9.5/main/postgresql.conf
    sudo sed -i "235 i max_replication_slots = 10" /etc/postgresql/9.5/main/postgresql.conf
    # NEEDS BETTER SECURITY
    sudo sed -i "92 i host    all             all             127.0.0.1/32            trust" /etc/postgresql/9.5/main/pg_hba.conf
    sudo sed -i "93 i host    all             all             192.168.33.101/32       trust" /etc/postgresql/9.5/main/pg_hba.conf
    sudo service postgresql restart
    sudo su postgres -c "createdb test"
    echo "CREATE EXTENSION pglogical;" | sudo su postgres -c "psql test"
    echo "create table table1 (id serial not null primary key, txt text);" | sudo su postgres -c "psql test"
    echo "SELECT pglogical.create_node(node_name := 'subscriber1', dsn := 'host=192.168.33.101 port=5432 dbname=test');" | sudo su postgres -c "psql test"
    echo "SELECT pglogical.create_subscription(subscription_name := 'subscription1', provider_dsn := 'host=192.168.33.100 port=5432 dbname=test');" | sudo su postgres -c "psql test"
  SHELL
end
